name: Build
on: [push]

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-latest

    env:
      # https://github.com/actions/setup-go/issues/14
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin

    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Setup
      run: |
        echo "::add-path::${GOBIN}"
        go get -u golang.org/x/lint/golint

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}

    - name: Linters
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      run: |
        make linters

  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}

    - name: Test
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      run: make unit_test
